[template]
# 模板文件
src = "config.conf.tmpl"
# 输出文件
dest = "./conf/conf.toml"

keys = [
    "/log_level",
    "/app/name",
    "/server/addr",
    "/server/ws_addr",
    "/auth/provider",
    "/auth/addrs",
    "/broker/provider",
    "/auth/addrs",
    "/sessions/provider",
    "/database/name",
    "/database/user_name",
    "/database/pwd",
    "/database/host",
    "/database/port",
    "/redis/server",
    "/redis/pwd",
    "/memcached/server",
    "/opentracing/disable",
    "/opentracing/type",
    "/opentracing/service_name",
    "/opentracing/address",
]